version: '3.2'

services:
  ms1:
     build: ../MS1
     ports:
         - "9001:9001"
     tty:
         true
     restart:
        unless-stopped
 
  ms2:
    build: ../MS2
    ports:
         - "9002:9002"
    tty:
      true
    restart:
      unless-stopped
      
  ms3:
    build: ../MS3
    ports:
         - "9003:9003"
    tty:
      true
    restart:
      unless-stopped
  
  gateway:
    build: ../gateway
    ports:
         - "9000:9000"
    tty:
      true
    restart:
      unless-stopped

  serviceregistry:
    build: ../serviceregistry
    ports:
         - "8671:8671"
    tty:
      true
    restart:
      unless-stopped
  
  config:
    build: ../config
    ports:
         - "8888:8888"
    tty:
      true
    restart:
      unless-stopped   
   
  